export // Mapa de conversión ISO3 a hc-key (ISO2 lowercase)
const iso3ToHcKey = {
    "ESP": "es", "USA": "us", "GBR": "gb", "FRA": "fr", "DEU": "de",
    "ITA": "it", "CHN": "cn", "IND": "in", "BRA": "br", "RUS": "ru",
    "CAN": "ca", "AUS": "au", "MEX": "mx", "KOR": "kr", "JPN": "jp",
    "ZAF": "za", "ARG": "ar", "EGY": "eg", "NGA": "ng", "TUR": "tr",
    "IDN": "id", "SAU": "sa", "PAK": "pk", "BGD": "bd", "NLD": "nl",
    "BEL": "be", "CHE": "ch", "SWE": "se", "NOR": "no", "DNK": "dk",
    "FIN": "fi", "POL": "pl", "AUT": "at", "PRT": "pt", "GRC": "gr",
    "CZE": "cz", "HUN": "hu", "ROU": "ro", "UKR": "ua", "SRB": "rs",
    "BGR": "bg", "HRV": "hr", "SVK": "sk", "SVN": "si", "LTU": "lt",
    "LVA": "lv", "EST": "ee", "BLR": "by", "MDA": "md", "ALB": "al",
    "MKD": "mk", "BIH": "ba", "MNE": "me", "XKX": "xk", "ISL": "is",
    "IRL": "ie", "LUX": "lu", "MLT": "mt", "CYP": "cy", "ISR": "il",
    "JOR": "jo", "LBN": "lb", "SYR": "sy", "IRQ": "iq", "IRN": "ir",
    "KWT": "kw", "QAT": "qa", "ARE": "ae", "OMN": "om", "YEM": "ye",
    "AFG": "af", "KAZ": "kz", "UZB": "uz", "TKM": "tm", "TJK": "tj",
    "KGZ": "kg", "MNG": "mn", "PRK": "kp", "TWN": "tw", "VNM": "vn",
    "THA": "th", "MYS": "my", "PHL": "ph", "SGP": "sg",
    "MMR": "mm", "KHM": "kh", "LAO": "la", "NPL": "np", "LKA": "lk",
    "BTN": "bt", "MDV": "mv", "MAR": "ma", "DZA": "dz",
    "TUN": "tn", "LBY": "ly", "SDN": "sd", "ETH": "et", "ERI": "er",
    "DJI": "dj", "SOM": "so", "KEN": "ke", "TZA": "tz", "UGA": "ug",
    "RWA": "rw", "BDI": "bi", "MOZ": "mz", "ZMB": "zm", "ZWE": "zw",
    "MWI": "mw", "AGO": "ao", "COD": "cd", "COG": "cg", "GAB": "ga",
    "CMR": "cm", "CAF": "cf", "TCD": "td", "NER": "ne", "MLI": "ml",
    "BFA": "bf", "GHA": "gh", "CIV": "ci", "GIN": "gn", "SEN": "sn",
    "GMB": "gm", "GNB": "gw", "SLE": "sl", "LBR": "lr",
    "BEN": "bj", "TGO": "tg", "GNQ": "gq", "STP": "st", "CPV": "cv",
    "MRT": "mr", "NAM": "na", "BWA": "bw", "LSO": "ls", "SWZ": "sz",
    "MDG": "mg", "MUS": "mu", "COM": "km", "SYC": "sc", "COL": "co",
    "VEN": "ve", "PER": "pe", "ECU": "ec", "BOL": "bo", "PRY": "py",
    "URY": "uy", "CHL": "cl", "GUY": "gy", "SUR": "sr", "TTO": "tt",
    "JAM": "jm", "CUB": "cu", "HTI": "ht", "DOM": "do", "PRI": "pr",
    "GTM": "gt", "BLZ": "bz", "HND": "hn", "SLV": "sv", "NIC": "ni",
    "CRI": "cr", "PAN": "pa", "NZL": "nz", "PNG": "pg", "FJI": "fj"
};