name: CI_CD
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build frontend
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Run server for playwright
        run: npm start &
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Execute playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30